#!/usr/bin/env bash
set -e # halt script on error
root_dir=`pwd`
build_books=`cat select_books`

for file in $build_books; do
	cd $root_dir
    if [ -d "$file" -a ! "$file" = script -a ! "$file" = node_modules ]; then
    	echo "entering dir: $file"
    	cd "$file"
        gitbook build
    fi
done
