#!/usr/bin/env bash
set -e # halt script on error
root_dir=`pwd`

for file in *; do
	cd $root_dir
    if [ -d "$file" -a ! "$file" = script -a ! "$file" = node_modules ]; then
    	cd "$file"
        gitbook install
    fi
done
